### ISSUE TITLE
Interested in collaborating with ModiTect?

### ISSUE THREAD

**Issue by gunnarmorling** [beryx/badass-jar#1]
Hey,

I just learned from @aalmiray about this plug-in and your blog post at https://beryx.org/blog/2018-11-21-/modular-jars-targeted-at-pre-java-9/. Thanks a lot for the reference to ModiTect! Having a Gradle plug-in for ModiTect has been on the wishlist for a while, and @aalmiray was just recently expressing interest towards contributing to such effort. Seeing your plug-in here, we were wondering whether you'd perhaps be interested in creating a joint effort under the ModiTect umbrella? 

Cheers,

Gunnar

**Comment by siordache** [comment]
Hi Gunnar,

Yes, I'm interested in collaborating with ModiTect and this plugin definitely belongs under its umbrella.

Cheers,
Serban

**Comment by siordache** [comment]
Happy new year, @gunnarmorling !

My original intention was to gradually transform this project into a Gradle plugin for ModiTect. However, I concluded that it's actually easier to start from scratch. Besides, I think it's convenient to have a simple plugin for the use case of creating modular jars that target a Java release before 9. That's why I decided to keep this project as a member of the [badass plugins family](https://plugins.gradle.org/search?term=badass) and to implement a new one as counterpart of the Maven ModiTect plugin.

The new project is currently located [here](https://github.com/beryx/moditect-gradle-plugin). While still in alpha stage, it's already able to create valid custom runtime images for the `hibernate-validator` and `undertow` test projects. The Gradle plugin uses the moditect artifact` as a dependency. I chose to put the plugin in a separate repository instead of providing it as a PR for the ModiTect project. This way, the Maven and the Gradle plugin can move at their own pace.

I will gladly transfer the Gradle plugin repository to the ModiTect organization if you find it useful. (For this, you need to [invite me](https://github.com/orgs/moditect/people) to become a member of the ModiTect organization.)

Cheers,
Serban

**Comment by gunnarmorling** [comment]
Hey @siordache, happy 2019 to you, too! Really excited to hear that you'd like team up with ModiTect for the Gradle plug-in! I've just sent you an invite for the "moditect" organization and created a repo for the plug-in: https://github.com/moditect/moditect-gradle-plugin. So you should be able to send a PR with your current implementation against that repo. I'll then take a look. Thanks a lot!

**Comment by siordache** [comment]
Thanks, @gunnarmorling ! I will send the PR in the next few days.
